spring:
  application:
    name: livro

  profiles:
    active: test

  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  port: ${port:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ms-livro:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      ms-usuario:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

management:
  endpoints:
    web:
      exposure:
        include: health
